NodeParam: &NodeParam {type: http, interval: 86400, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 300},filter: '^(?!.*2\.00).*$'}

proxy-providers:
  SS-ShadowTLS:
    url: "http://10.0.0.200:23301/daxiong828/download/SS-ShadowTLS?target=ClashMeta"   #source:https://github.com/wzdnzd/aggregator/issues/91
    <<: *NodeParam
    path: ./proxy_providers/SS-ShadowTLS.yaml
    override:
      additional-prefix: "SS-ShadowTLS"

proxies:

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
ipv6: true
allow-lan: true
mode: rule
log-level: info
unified-delay: false
tcp-concurrent: true
external-controller: '0.0.0.0:9090'
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
find-process-mode: strict
global-client-fingerprint: chrome
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    - "+.weixin.qq.com"
    - "+.wechat.com"
    - "+.wx.qq.com"
    - "+.tenpay.com"
    - "+.qq.com"
    - "+.qpic.cn"
    - "+.qlogo.cn"
    - "+.mmbiz.qpic.cn"
    - "+.mmbiz.qlogo.cn"
    - "+.mmbizurl.cn"
    - "+.weibo.cn"
    - "+.weibo.com"
    - "+.douyin.com"
    - "+.douyinpic.com"
    - "+.kuaishou.com"
    - "+.zhihu.com"
    - "+.taobao.com"
    - "+.tmall.com"
    - "+.alipay.com"
    - "+.jd.com"
    - "+.bilibili.com"
    - "+.bilibili.tv"
    - "+.amap.com"
    - "+.iqiyi.com"
    - "+.youku.com"
    - "+.mgtv.com"
    - "+.mi.com"
    - "+.xiaomi.com"
    - "+.icloud.com.cn"
    - "+.baidu.com"
    - "+.bytedance.com"
tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
dns:
  enable: true
  prefer-h3: true
  cache-algorithm: arc
  ipv6: true  # ä¿ç•™IPv6è§£æž
  respect-rules: true
  prefer-ipv4: true  # ä¼˜å…ˆä½¿ç”¨IPv4è§£æž
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.lan"
    - "+.local"
  default-nameserver:
    - https://223.5.5.5/dns-query
  nameserver: #é»˜è®¤çš„åŸŸåè§£æžæœåŠ¡å™¨ã€‚
    - system
    - https://dns.alidns.com/dns-query # é˜¿é‡Œ
    - https://doh.pub/dns-query # è…¾è®¯
  proxy-server-nameserver: # ä»£ç†æœåŠ¡å™¨çš„ DNS è§£æžï¼Œä»…ç”¨äºŽè§£æžä»£ç†èŠ‚ç‚¹çš„åŸŸåã€‚
    - https://dns.alidns.com/dns-query # é˜¿é‡Œ
    - https://dns.cloudflare.com/dns-query # Cloudflare
  fallback:
    - "https://dns.cloudflare.com/dns-query"
    - "https://dns.google/dns-query"
    - 8.8.4.4
    - 1.1.1.1
  direct-nameserver:
    - quic://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query
  fallback-filter:
    geoip: true  # é¿å…fallbackä½¿ç”¨IPv6çš„DNS
    ipcidr:
      - 2400::/4  # é˜»æ­¢ä½¿ç”¨IPv6 fallback DNS

proxy-groups: #åˆ†æµåˆ†ç»„
  - {name: æ‰‹åŠ¨åˆ‡æ¢, type: select, proxies: [DIRECT, è‡ªåŠ¨é€‰æ‹©, ç¾Žå›½èŠ‚ç‚¹, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png}
  - {name: å…¨çƒåŠ é€Ÿ, type: select, proxies: [æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, ç¾Žå›½èŠ‚ç‚¹, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png}
  - {name: è‹¹æžœæœåŠ¡, type: select, proxies: [DIRECT, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾Žå›½èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Apple.png}
  - {name: YouTube, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/YouTube.png}
  - {name: Spotify, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶],icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Spotify.png}
  - {name: TikTok, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/TikTok.png}
  - {name: Telegram, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png}
  - {name: Twitter, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Twitter.png}
  - {name: GitHub, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/github.png}
  - {name: äººå·¥æ™ºèƒ½, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/OpenAI.png}
  - {name: å›½é™…åª’ä½“, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Streaming.png}
  - {name: è°·æ­ŒæœåŠ¡, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png}
  - {name: ç¤¾äº¤åª’ä½“, type: select, proxies: [ç¾Žå›½èŠ‚ç‚¹, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png}
  - {name: åŠ å¯†è´§å¸, type: select, proxies: [é¦™æ¸¯èŠ‚ç‚¹, DIRECT, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, ç¾Žå›½èŠ‚ç‚¹, éŸ©å›½èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Bitcloud.png}
  - {name: æ¸¸æˆå¹³å°, type: select, proxies: [DIRECT, æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, ç¾Žå›½èŠ‚ç‚¹, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/GAME.png}
  - {name: å…œåº•åˆ†æµ, type: select, proxies: [æ‰‹åŠ¨åˆ‡æ¢, è‡ªåŠ¨é€‰æ‹©, DIRECT, ç¾Žå›½èŠ‚ç‚¹, éŸ©å›½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç‹®åŸŽèŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¶ä»–å›½å®¶], icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Final.png}
#èŠ‚ç‚¹åˆ†ç»„
  - {name: è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, interval: 600, tolerance: 50, icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Speedtest.png}
  - {name: éŸ©å›½èŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)éŸ©|\\bkr\\b|korea|south korea|ðŸ‡°ðŸ‡·", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/KR.png}
  - {name: é¦™æ¸¯èŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)æ¸¯|hk|HK|hongkong|hong kong|ðŸ‡­ðŸ‡°", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png}
  - {name: æ—¥æœ¬èŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)æ—¥|jp|JP|japan|ðŸ‡¯ðŸ‡µ", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png}
  - {name: å°æ¹¾èŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)å°|tw|TW|taiwan|ðŸ‡¹ðŸ‡¼", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/TW.png}
  - {name: ç¾Žå›½èŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)ç¾Ž|us|US|unitedstates|united states|ðŸ‡ºðŸ‡²", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png}
  - {name: ç‹®åŸŽèŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)å¡|æ–°|SG|sg|singapore|ðŸ‡¸ðŸ‡¬", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/SG.png}
  - {name: æ¬§æ´²èŠ‚ç‚¹, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "(?i)ðŸ‡¦ðŸ‡±|ðŸ‡¦ðŸ‡©|ðŸ‡¦ðŸ‡¹|ðŸ‡§ðŸ‡¾|ðŸ‡§ðŸ‡ª|ðŸ‡§ðŸ‡¦|ðŸ‡§ðŸ‡¬|ðŸ‡­ðŸ‡·|ðŸ‡¨ðŸ‡¾|ðŸ‡¨ðŸ‡¿|ðŸ‡©ðŸ‡°|ðŸ‡ªðŸ‡ª|ðŸ‡«ðŸ‡®|ðŸ‡«ðŸ‡·|ðŸ‡©ðŸ‡ª|ðŸ‡¬ðŸ‡·|ðŸ‡­ðŸ‡º|ðŸ‡®ðŸ‡¸|ðŸ‡®ðŸ‡ª|ðŸ‡®ðŸ‡¹|ðŸ‡±ðŸ‡»|ðŸ‡±ðŸ‡®|ðŸ‡±ðŸ‡¹|ðŸ‡±ðŸ‡º|ðŸ‡²ðŸ‡¹|ðŸ‡²ðŸ‡©|ðŸ‡²ðŸ‡¨|ðŸ‡²ðŸ‡ª|ðŸ‡³ðŸ‡±|ðŸ‡²ðŸ‡°|ðŸ‡³ðŸ‡´|ðŸ‡µðŸ‡±|ðŸ‡µðŸ‡¹|ðŸ‡·ðŸ‡´|ðŸ‡·ðŸ‡º|ðŸ‡¸ðŸ‡²|ðŸ‡·ðŸ‡¸|ðŸ‡¸ðŸ‡°|ðŸ‡¸ðŸ‡®|ðŸ‡ªðŸ‡¸|ðŸ‡¸ðŸ‡ª|ðŸ‡¨ðŸ‡­|ðŸ‡ºðŸ‡¦|ðŸ‡¬ðŸ‡§|ðŸ‡»ðŸ‡¦|ðŸ‡¦ðŸ‡¿|ðŸ‡¬ðŸ‡ª|ðŸ‡¦ðŸ‡²|ðŸ‡°ðŸ‡¿|ðŸ‡¹ðŸ‡·", icon: https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/European.png}
  - {name: å…¶ä»–å›½å®¶, type: url-test, include-all: true, interval: 600, tolerance: 50, filter: "^(?!.*(éŸ©|\\bkr\\b|korea|south korea|ðŸ‡°ðŸ‡·|æ¸¯|hk|HK|hongkong|hong kong|ðŸ‡­ðŸ‡°|æ—¥|jp|JP|japan|ðŸ‡¯ðŸ‡µ|å°|tw|TW|taiwan|ðŸ‡¹ðŸ‡¼|ç¾Ž|us|US|unitedstates|united states|ðŸ‡ºðŸ‡²|å¡|æ–°|SG|sg|singapore|ðŸ‡¸ðŸ‡¬|ðŸ‡¦ðŸ‡±|ðŸ‡¦ðŸ‡©|ðŸ‡¦ðŸ‡¹|ðŸ‡§ðŸ‡¾|ðŸ‡§ðŸ‡ª|ðŸ‡§ðŸ‡¦|ðŸ‡§ðŸ‡¬|ðŸ‡­ðŸ‡·|ðŸ‡¨ðŸ‡¾|ðŸ‡¨ðŸ‡¿|ðŸ‡©ðŸ‡°|ðŸ‡ªðŸ‡ª|ðŸ‡«ðŸ‡®|ðŸ‡«ðŸ‡·|ðŸ‡©ðŸ‡ª|ðŸ‡¬ðŸ‡·|ðŸ‡­ðŸ‡º|ðŸ‡®ðŸ‡¸|ðŸ‡®ðŸ‡ª|ðŸ‡®ðŸ‡¹|ðŸ‡±ðŸ‡»|ðŸ‡±ðŸ‡®|ðŸ‡±ðŸ‡¹|ðŸ‡±ðŸ‡º|ðŸ‡²ðŸ‡¹|ðŸ‡²ðŸ‡©|ðŸ‡²ðŸ‡¨|ðŸ‡²ðŸ‡ª|ðŸ‡³ðŸ‡±|ðŸ‡²ðŸ‡°|ðŸ‡³ðŸ‡´|ðŸ‡µðŸ‡±|ðŸ‡µðŸ‡¹|ðŸ‡·ðŸ‡´|ðŸ‡·ðŸ‡º|ðŸ‡¸ðŸ‡²|ðŸ‡·ðŸ‡¸|ðŸ‡¸ðŸ‡°|ðŸ‡¸ðŸ‡®|ðŸ‡ªðŸ‡¸|ðŸ‡¸ðŸ‡ª|ðŸ‡¨ðŸ‡­|ðŸ‡ºðŸ‡¦|ðŸ‡¬ðŸ‡§|ðŸ‡»ðŸ‡¦|ðŸ‡¦ðŸ‡¿|ðŸ‡¬ðŸ‡ª|ðŸ‡¦ðŸ‡²|ðŸ‡°ðŸ‡¿|ðŸ‡¹ðŸ‡·)).*$", icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/UN.png}


rule-anchor: # è§„åˆ™é”šç‚¹
  classical: &classical {type: http, interval: 86400, behavior: classical, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
  ipcidr: &ipcidr {type: http, interval: 86400, behavior: ipcidr, format: yaml}
rule-providers: # åˆ†æµè§„åˆ™ 
  My_Direct: {<<: *classical, url: https://raw.githubusercontent.com/xiongking/clash_rules/refs/heads/main/direct.yaml, path: ./ruleset/My_Direct.yaml}
  My_Proxy: {<<: *classical, url: https://raw.githubusercontent.com/xiongking/clash_rules/refs/heads/main/proxy.yaml, path: ./ruleset/My_Proxy.yaml}
  DECOTV: {<<: *classical, url: https://raw.githubusercontent.com/xiongking/clash_rules/refs/heads/main/decotv.yaml, path: ./ruleset/decotv.yaml}
  Crypt: {<<: *classical, url: https://raw.githubusercontent.com/xiongking/clash_rules/refs/heads/main/crypt.yaml, path: ./ruleset/crypt.yaml}
  Tencent: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.yaml, path: ./ruleset/Tencent.yaml}
  XiaoHongShu: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoHongShu/XiaoHongShu.yaml, path: ./ruleset/XiaoHongShu.yaml}
  Alibaba: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba_Classical.yaml, path: ./ruleset/Alibaba.yaml}
  Baidu: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Baidu/Baidu.yaml, path: ./ruleset/Baidu.yaml}
  DouYin: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/DouYin/DouYin.yaml, path: ./ruleset/DouYin.yaml}
  ByteDance: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/ByteDance/ByteDance.yaml, path: ./ruleset/ByteDance.yaml}
  BiliBili: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml, path: ./ruleset/BiliBili.yaml}
  YouTube: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml, path: ./ruleset/YouTube.yaml}
  GitHub: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml, path: ./ruleset/GitHub.yaml}
  Spotify: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml, path: ./ruleset/Spotify.yaml}
  TikTok: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml, path: ./ruleset/TikTok.yaml}
  Telegram: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml, path: ./ruleset/Telegram.yaml}
  Twitter: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml, path: ./ruleset/Twitter.yaml}
  Ai: {<<: *classical, url: https://raw.githubusercontent.com/xiongking/clash_rules/refs/heads/main/ai.yaml, path: ./ruleset/Ai.yaml}
  OpenAi: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml, path: ./ruleset/OpenAi.yaml}
  Gemini: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml, path: ./ruleset/Gemini.yaml}
  Claude: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml, path: ./ruleset/Claude.yaml}
  Copilot: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml, path: ./ruleset/Copilot.yaml}
  Anthropic: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Anthropic/Anthropic.yaml, path: ./ruleset/Anthropic.yaml}
  GlobalMedia: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml, path: ./ruleset/GlobalMedia.yaml}
  Apple: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical.yaml, path: ./ruleset/Apple.yaml}
  Github: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml, path: ./ruleset/Github.yaml}
  Microsoft: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml, path: ./ruleset/Microsoft.yaml}
  Google: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml, path: ./ruleset/Google.yaml}
  Reddit: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Reddit/Reddit.yaml, path: ./ruleset/Reddit.yaml}
  Game: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml, path: ./ruleset/Game.yaml}
  ProxyLite: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.yaml, path: ./ruleset/ProxyLite.yaml}
  Direct: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml, path: ./ruleset/Direct.yaml}
  Lan: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml, path: ./ruleset/Lan.yaml}
  Download: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml, path: ./ruleset/Download.yaml}
  China_Classical: {<<: *classical, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml, path: ./ruleset/China_Classical.yaml}
  ChinaIP: {<<: *ipcidr, url: https://raw.githubusercontent.com/soffchen/GeoIP2-CN/release/clash-rule-provider.yml, path: ./ruleset/ChinaIP.yaml}
rules: # åˆ†æµPolicy
  - RULE-SET,My_Proxy,å…¨çƒåŠ é€Ÿ
  - RULE-SET,My_Direct,DIRECT
  - RULE-SET,DECOTV,DIRECT
  - RULE-SET,Crypt,åŠ å¯†è´§å¸
  - DOMAIN,xnâ€“ngstr-cn-8za9o.com,è°·æ­ŒæœåŠ¡
  - DOMAIN,clientservices.googleapis.com,è°·æ­ŒæœåŠ¡
  - RULE-SET,Tencent,DIRECT
  - RULE-SET,XiaoHongShu,DIRECT
  - RULE-SET,Alibaba,DIRECT
  - RULE-SET,Baidu,DIRECT
  - RULE-SET,DouYin,DIRECT
  - RULE-SET,ByteDance,DIRECT
  - RULE-SET,BiliBili,DIRECT
  - RULE-SET,Ai,äººå·¥æ™ºèƒ½
  - RULE-SET,OpenAi,äººå·¥æ™ºèƒ½
  - RULE-SET,Gemini,äººå·¥æ™ºèƒ½
  - RULE-SET,Claude,äººå·¥æ™ºèƒ½
  - RULE-SET,Copilot,äººå·¥æ™ºèƒ½
  - RULE-SET,Anthropic,äººå·¥æ™ºèƒ½
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Spotify,Spotify
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Twitter,Twitter
  - RULE-SET,GitHub,GitHub
  - RULE-SET,GlobalMedia,å›½é™…åª’ä½“
  - RULE-SET,Apple,è‹¹æžœæœåŠ¡
  - RULE-SET,Github,å…¨çƒåŠ é€Ÿ
  - RULE-SET,Reddit,ç¤¾äº¤åª’ä½“
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,BiliBili,DIRECT
  - RULE-SET,Google,è°·æ­ŒæœåŠ¡
  - RULE-SET,Game,æ¸¸æˆå¹³å°
  - RULE-SET,ProxyLite,å…¨çƒåŠ é€Ÿ
  - RULE-SET,China_Classical,DIRECT
  - RULE-SET,ChinaIP,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Lan,DIRECT
  - RULE-SET,Download,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,å…œåº•åˆ†æµ
